export const adminStoreSummary = {
  totalStores: 126,
  activeStores: 121,
  riskStores: 7,
  pendingInspections: 8,
  contractExpiring: 5,
}

export const adminStores = [
  {
    name: '강남역점',
    owner: '김도윤',
    region: '서울 강남구',
    sales: '₩4,820,000',
    monthlySales: '₩38,520,000',
    hygieneScore: 72,
    risk: '높음',
    contractStatus: '정상',
    lastInspection: '오늘 09:40',
    issue: '조리대 청결 재확인 필요',
    phone: '010-4820-1593',
    address: '서울 강남구 테헤란로 18길 12',
    storeCode: 'ST-GANGNAM',
    source: 'DEMO' as 'DEMO' | 'IMPORTED',
  },
  {
    name: '성수점',
    owner: '이서준',
    region: '서울 성동구',
    sales: '₩5,140,000',
    monthlySales: '₩42,180,000',
    hygieneScore: 94,
    risk: '안전',
    contractStatus: '정상',
    lastInspection: '오늘 08:55',
    issue: '특이사항 없음',
    phone: '010-7412-8850',
    address: '서울 성동구 연무장길 42',
    storeCode: 'ST-SEONGSU',
    source: 'DEMO' as 'DEMO' | 'IMPORTED',
  },
  {
    name: '잠실점',
    owner: '박지우',
    region: '서울 송파구',
    sales: '₩3,760,000',
    monthlySales: '₩31,440,000',
    hygieneScore: 86,
    risk: '보통',
    contractStatus: '재계약 검토',
    lastInspection: '어제 18:20',
    issue: '월 매출 목표 미달 가능성',
    phone: '010-3387-2140',
    address: '서울 송파구 올림픽로 35길 10',
    storeCode: 'ST-JAMSIL',
    source: 'DEMO' as 'DEMO' | 'IMPORTED',
  },
  {
    name: '여의도점',
    owner: '최하늘',
    region: '서울 영등포구',
    sales: '₩4,250,000',
    monthlySales: '₩35,960,000',
    hygieneScore: 91,
    risk: '안전',
    contractStatus: '정상',
    lastInspection: '오늘 10:15',
    issue: '특이사항 없음',
    phone: '010-9061-3724',
    address: '서울 영등포구 국제금융로 8길 16',
    storeCode: 'ST-YEOUIDO',
    source: 'DEMO' as 'DEMO' | 'IMPORTED',
  },
  {
    name: '부산서면점',
    owner: '정민호',
    region: '부산 부산진구',
    sales: '₩2,980,000',
    monthlySales: '₩25,320,000',
    hygieneScore: 69,
    risk: '높음',
    contractStatus: '주의',
    lastInspection: '어제 16:10',
    issue: '위생 점수 하락 및 매출 감소',
    phone: '010-6112-4409',
    address: '부산 부산진구 중앙대로 692',
    storeCode: 'ST-BUSAN',
    source: 'DEMO' as 'DEMO' | 'IMPORTED',
  },
]

export const actionRequiredStores = [
  {
    store: '강남역점',
    title: '위생 점검 재확인 필요',
    description: 'AI 사진 분석 결과 조리대 청결 상태가 기준보다 낮게 측정되었습니다.',
    priority: '긴급',
  },
  {
    store: '부산서면점',
    title: '운영 리스크 상담 필요',
    description: '최근 2주간 매출 감소와 위생 점수 하락이 동시에 발생했습니다.',
    priority: '긴급',
  },
  {
    store: '잠실점',
    title: '재계약 조건 검토',
    description: '계약 갱신 전 매출 목표 달성률과 운영 안정성 검토가 필요합니다.',
    priority: '주의',
  },
]

export const regionStats = [
  { region: '서울', stores: 82, risk: 4 },
  { region: '부산', stores: 18, risk: 2 },
  { region: '대구', stores: 11, risk: 1 },
  { region: '기타', stores: 15, risk: 0 },
]